//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookShopDao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookRatings = new HashSet<BookRating>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ReaderComments = new HashSet<ReaderComment>();
            this.RecomBooks = new HashSet<RecomBook>();
            this.TemporaryCarts = new HashSet<TemporaryCart>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int PublisherId { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string ISBN { get; set; }
        public decimal UnitPrice { get; set; }
        public string ContentDescription { get; set; }
        public string TOC { get; set; }
        public int CategoryId { get; set; }
        public int Clicks { get; set; }
    
        public virtual ICollection<BookRating> BookRatings { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual ICollection<ReaderComment> ReaderComments { get; set; }
        public virtual ICollection<RecomBook> RecomBooks { get; set; }
        public virtual ICollection<TemporaryCart> TemporaryCarts { get; set; }
    }
}
