//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookShopDao.Model
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BookRatings = new HashSet<BookRating>();
            this.Orders = new HashSet<Order>();
            this.RecomBooks = new HashSet<RecomBook>();
            this.TemporaryCarts = new HashSet<TemporaryCart>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "账号不能为空")]
        [Display(Name = "登录名")]
        public string LoginId { get; set; }
        [Required(ErrorMessage = "密码不能为空")]
        [StringLength(10, MinimumLength = 3, ErrorMessage = "密码长度至少为3")]
        [Display(Name = "密码")]
        public string LoginPwd { get; set; }
        [Required(ErrorMessage = "重复密码不能为空")]
        [Compare("LoginPwd", ErrorMessage = "密码不相同")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "真实姓名不能为空")]
        [Display(Name = "姓名")]
        public string Name { get; set; }
        [Required(ErrorMessage = "地址不能为空")]
        [Display(Name = "地址")]
        public string Address { get; set; }
        [Required(ErrorMessage = "电话不能为空")]
        [Display(Name = "电话")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "电子邮件不能为空")]
        [RegularExpression(@"\w+@\w+\.[a-z]{2,3}(\.[a-z]{2,3})?", ErrorMessage = "邮件不合法")]
        [Display(Name = "电子邮件")]
        public string Mail { get; set; }
        public int UserRoleId { get; set; }
        public bool UserState { get; set; }
    
        public virtual ICollection<BookRating> BookRatings { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<RecomBook> RecomBooks { get; set; }
        public virtual ICollection<TemporaryCart> TemporaryCarts { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
